# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=256)),
                ('photo', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('saleNum', models.IntegerField()),
                ('commentsNum', models.IntegerField()),
                ('isxf', models.IntegerField()),
                ('brandid', models.IntegerField()),
                ('placeid', models.IntegerField()),
                ('suitid', models.IntegerField()),
                ('goodsid', models.IntegerField()),
            ],
            options={
                'db_table': 'zj_market',
            },
        ),
        migrations.CreateModel(
            name='shoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Goods')),
            ],
            options={
                'db_table': 'zj_shoppingcart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('addr', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'zj_users',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'zj_wheel',
            },
        ),
        migrations.CreateModel(
            name='whiteSpirit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('typeid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'zj_whiteSpirit',
            },
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users'),
        ),
    ]
